### ISSUE TITLE
AnimationListener in RippleDrawable/RippleDrawableCompat

### ISSUE THREAD

**Issue by borgwald** [ZieIony/Carbon#124]
Hello,

i have a recyclerview with cardview. i have setup a rippledrawable for the cardview in my viewholder like in your example. 

furthermore i have set an onclicklistener on the viewholder. 

maybe there is a possibilty to implement an animationlistener that listens for the ending of the rippleeffect animation? i want to have the clickevent happen when the animation finishes because the rippleeffect then looks more fluid.

**Comment by ZieIony** [comment]
Hello there,

It's not possible, because Lollipop's version doesn't have any listener I could use. Carbon reuses Lollipop's classes on compatible devices. I could implement a listener for compat version only, but it would complicate the code. If you wish, you can add a fixed delay in your code.

The second reason is that delaying actions leads to race conditions between a user and a device. The user may tap a buton multiple times before it triggers an action due to the ripple delay. That's why delaying actions is not recommended.

Android M changed the ripple touch feedback so the animation starts after lifting the finger. This may help as the animation won't start at all under heavy cpu load.
