### ISSUE TITLE
How do I set state drawables with "transparent" states on elevated views with shadow?

### ISSUE THREAD

**Issue by NeverGivinUp** [ZieIony/Carbon#139]
Elevated views throw a shadow. That's great! Trouble is, the shadow is drawn not just outside the view, but also on the inside -- on pre-Lollipop devices anyway. To still make it look like a realistic shadow, I set the background of views that should have a transparent background to ?android:attr/colorBackground. With views, that's background needs to depend on their state (e.g. selectable elements of a list) , I can't do that though, as android cannot handle attribute references in state drawables. I can't use a static color either, as android only assures that a light theme will have a light background, but not how light or what hue. How can I handle elevated, state dependent views?

**Comment by ZieIony** [comment]
On Lollipop each shadow is a part of its corresponding view and it's drawn as a part of it. Carbon draws shadows beneath views, because on older Androids it's impossible to draw outside view's bounds from that view. It's something what I would like to fix, but I have no idea, where to start.

Nested references are supported on Android 5.+, so you're right, it's really tricky.

For now there are two solutions. One of them is to wrap a view with a layout and use alpha transformations, so transparency is applied to the view and its shadow at once. The second one is to create a state drawable from code, just like default state drawables provided by Carbon.

See: https://github.com/ZieIony/Carbon/blob/master/carbon/src/main/java/carbon/drawable/ControlAccentColorStateList.java

**Comment by NeverGivinUp** [comment]
For now I'll go with the state drawable from code. 

Can you explain in some more detail how lollipop devices draw shadows? Do they them in the draw/ onDraw method , but outside its bounds (outside padding), where views normally cannot draw? 

You have layouts draw shadows of views they contain, right? 

For elevated views I think that is practically an ideal solution. The only problem is the form of the (let's call it) "shadow drawable". The shadow drawable should be transparent within the outline of the view. But the shadow drawable has non- or semi-transparent parts below the view. Stamping out the outline of the view would be a solution. The technique I know is rather slow, though...

For recessed views the shadow drawable should be on top of the view (I don't know if it already does so. Nor do I know how Lollipop handles them.)

**Comment by ZieIony** [comment]
As far as I know, shadows are drawn using OpenGL in HardwareCanvas::drawRenderNode() method. It's all native code, so there's no padding, bounds, elevation, etc. Just textures, a screen buffer and a drawing shader.

Yes. On older devices all of the drawing is done using screen-size offscreen buffers (textures), which are transformed so both the buffer and the corresponding view start in [0,0]. Then each view is drawn and composited with other layers. Basically if the drawing starts at [0,0], it's not possible to draw to the left of and above the view. I'm not sure if I'm clear and I don't know the reason behind the drawing flow, but more or less this is how it works.

Clipping shadows on older platforms is possible, but yes - it's pretty expensive. Lollipop clips shadows using convex paths which are available since Android 4.3. I think I have an idea how to make it work, but I have to code and test it first to say more about its viability.

Views can only have positive elevation, so for recessed views you need a background view and a two or more views on top of the background casting shadows on it.

And a weird thought - semi-transparent objects do cast semi-transparent shadows in real life so Carbon is more accurate than Lollipop :)

**Comment by NeverGivinUp** [comment]
The trouble with convex paths seems to be, that they only support convex curves. So even a star shape is out of the question. 

Honestly I fear this shadow stuff is beyond me :-(
There are a number of old "recipes" from Romain Guy that might contain interesting ideas (if you don't know them already). But I can't find THE right one. They are the following http://www.curious-creature.com/2012/12/11/android-recipe-1-image-with-rounded-corners/
http://www.curious-creature.com/2012/12/13/android-recipe-2-fun-with-shaders/
http://www.curious-creature.com/2012/12/14/android-recipe-3-sliding-menu-layers-and-filters/
http://www.curious-creature.com/2013/12/21/android-recipe-4-path-tracing/

I created the following StateListDrawable. You can offer it (or a variation of it) as part of carbon, if you like.

``` java
package carbon.util;

import android.content.Context;
import android.content.res.Resources;
import android.graphics.drawable.ColorDrawable;
import android.graphics.drawable.Drawable;
import android.graphics.drawable.StateListDrawable;
import android.support.annotation.DrawableRes;

/**
 * Represents "transparent" color in default state and activated color in enabled state.
 * FIXME: This really is a hack. When pre-lollipop devices allow xml color state lists allow referencing attributes, replace by xml color state list.
 * Like {@code <?xml version="1.0" encoding="utf-8"?>
 * <selector xmlns:android="http://schemas.android.com/apk/res/android">
 * <item android:drawable="@color/primary" android:state_activated="true"/>
 * <item android:drawable="@color/primary" android:state_pressed="true"/>
 * <item android:drawable="?android:attr/colorBackground"/>
 * </selector>}
 * When carbon draws shadows only outside views, replace by xml color state list with transparent backgrounds.
 * Like {@code <?xml version="1.0" encoding="utf-8"?>
 * <selector xmlns:android="http://schemas.android.com/apk/res/android">
 * <item android:drawable="@color/primary" android:state_activated="true"/>
 * <item android:drawable="@color/primary" android:state_pressed="true"/>
 * <item android:drawable="@android:color/transparent"/>
 * </selector>}
 */
public class ActivatedBackgroundDrawable extends StateListDrawable {

    /**
     * Creates a {@link StateListDrawable} with {@code android.R.attr.windowBackground} as default color and the color from {@code activatedColorResId} as color for the
     * pressed and the activated state.
     */
    public static StateListDrawable getForActivity(final Context context, @DrawableRes final int activatedColorResId) {
        return new ActivatedBackgroundDrawable(
                context.getResources(),
                new int[][]{
                        new int[]{android.R.attr.state_activated},
                        new int[]{android.R.attr.state_pressed},
                        new int[]{}
                },
                new Drawable[]{
                        context.getResources().getDrawable(activatedColorResId),
                        context.getResources().getDrawable(activatedColorResId),
                        ThemeUtil.getThemeAttrDrawable(context, android.R.attr.windowBackground)
                });
    }

    /**
     * Creates a {@link StateListDrawable} with {@code android.R.attr.colorBackground} as default color and the color from {@code activatedColorResId} as color for the
     * pressed and the activated state.
     */
    public static StateListDrawable getForDialoge(final Context context, @DrawableRes final int activatedColorResId) {
        return new ActivatedBackgroundDrawable(
                context.getResources(),
                new int[][]{
                        new int[]{android.R.attr.state_activated},
                        new int[]{android.R.attr.state_pressed},
                        new int[]{}
                },
                new Drawable[]{
                        context.getResources().getDrawable(activatedColorResId),
                        context.getResources().getDrawable(activatedColorResId),
                        new ColorDrawable(ThemeUtil.getThemeAttrColor(context, android.R.attr.colorBackground))
                });
    }

    protected ActivatedBackgroundDrawable(final Resources res, final int[][] states, final Drawable[] drawables) {
        if (states.length != drawables.length)
            throw new IllegalArgumentException("lenght of states (" + states.length + ") != lenght of drawableResIds (" + drawables.length + ")");
        for (int i = 0; i < states.length; i++) {
            addState(states[i], drawables[i]);
        }
    }

}
```

**Comment by ZieIony** [comment]
Done
