### ISSUE TITLE
Support for ListView

### ISSUE THREAD

**Issue by wasdennnoch** [ZieIony/Carbon#153]
I was surprised when I found out that there is no ListView (or GridView) class that implements those fancy overscroll glows, it shouldn't be that hard to implement them, should it? :D

**Comment by ZieIony** [comment]
No, it's pretty easy, but it's not the reason Carbon lacks ListView and GridView. These classes have issues with highlighting rows, animations, recycling items and others. RecyclerView is much better and is updated more frequently. That's why I decided to drop support for ListView and GridView and I encourage you to switch to Recycler as well.
