### ISSUE TITLE
dependencies is not update

### ISSUE THREAD

**Issue by reaper12** [ZieIony/Carbon#178]
current version :0.11.0

**Comment by ZieIony** [comment]
That's right, current stable release is 0.11.0.

I always try to test each release on several different phones and tablets, check if old features are not broken, prepare samples, etc. That's why 0.12.0 is not released yet. I would like to finish SeekBar, RangeSeekBar, EditText, TableView and TableLayout for 0.12.0.

If you wish to use the most recent build in your app, you can use JitPack, as described here: https://github.com/ZieIony/Carbon/wiki/Installation
