### ISSUE TITLE
button ripple effect is not shown

### ISSUE THREAD

**Issue by mneckoee** [ZieIony/Carbon#207]
Hi, I use your button, but when I pressed it the background get orange instead of ripple effect, what did I miss? My Android version is 4.4.2

**Comment by ZieIony** [comment]
Did you go through the installation page? Make sure that:
- you have RenderScript configured correctly
- you're using one of Carbon's themes
- you're using one version of Carbon in all modules. Don't add support libraries - Carbon has correct ones inside.

You can find the installation guide here:
https://github.com/ZieIony/Carbon/wiki/Installation

If so, tell me:
- which version are you using (0.12.0, the most recent commit, other)?
- is the sample app working for you?
- are you doing anything extra with your button?

**Comment by mneckoee** [comment]
thank you man, I didn't set the theme correctly.

**Comment by rhonyabdullah** [comment]
This 

> you're using one version of Carbon in all modules. Don't add support libraries - Carbon has correct ones inside.

has given me more understanding about your carbon lib, so i'm going to carbon [build.gradle](https://github.com/ZieIony/Carbon/blob/master/carbon/build.gradle) file and found the support lib has been implemented, simply my build.gradle (app) looks like this:

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'tk.zielony:carbon:0.12.0'
}

of course extending AppCompatActiviy and another **appcompat** widget/dependency is available because this carbon lib already use that.

Thanks.
