### ISSUE TITLE
RecyclerView EdgeEffect drawn below children

### ISSUE THREAD

**Issue by Teja-Konjeti** [ZieIony/Carbon#227]
I use this library in my app. I have also set the overscroll mode to always but still edgeeffect is not working.
Library - https://github.com/h6ah4i/android-advancedrecyclerview

**Comment by ZieIony** [comment]
It's not my library. Are you using it with Carbon somehow? Could you please clarify that?

**Comment by Teja-Konjeti** [comment]
It's a recycler view adapter and I'm using it with your recycler view

**Comment by Teja-Konjeti** [comment]
Nd edge effect with that adapter is working fine on support v7 recycler view

**Comment by Teja-Konjeti** [comment]
Carbon's Edge effect was working fine with this adapter before edge effect compat was made final in 23.2

**Comment by ZieIony** [comment]
Are you using the most recent commit? I had to rewrite EdgeEffect and RecyclerView due to that change in support library. Now it should be fine. 23.2 - compatible RecyclerView will be present in Carbon 0.13.0

**Comment by Teja-Konjeti** [comment]
Yes, that's what I was taking about after that it's not working I'm using your library as a module with the latest commit

**Comment by Teja-Konjeti** [comment]
*talking

**Comment by ZieIony** [comment]
Could you please prepare a minimal application showing your issue? You have better understanding of the other library than me. I would like to debug your case on real code. Zip file with a project would be fine.

**Comment by Teja-Konjeti** [comment]
Yep! will txt u when it's done

**Comment by Teja-Konjeti** [comment]
Found it! Finally after 5 Hours... !!! The Effect isn't working if there are no ItemDecorations but working fine if there are!, I also found that in the library I was using they added the EdgeEffect as a Decoration to the RecyclerView, you can check that out and implement the same in your library. Do comment here as soon as it is done!!

**Comment by Teja-Konjeti** [comment]
Do you still want me to upload the sample code?

**Comment by Teja-Konjeti** [comment]
And yet another bug, EdgeEffect is not being shown when reaching the top while scrolling. I mean, I scrolled... the canvas is scrolling and the touch has been released... now the list reaches top but the speed is not zero and the EdgeEffect is supposed to absorb this which is not the case.

**Comment by Teja-Konjeti** [comment]
Do you want me to upload the sample?

**Comment by ZieIony** [comment]
If I understood correctly, it's an issue between Carbon and android-advancedrecyclerview, not in Carbon itself.

Carbon has EdgeEffect implemented in the way it's done in the regular RecyclerView, without using item decorations. Item decorations are used for drawing item dividers. EdgeEffect works fine for me, no matter if there is a decoration or not.

Carbon's RecyclerView doesn't have absorbtion effect, because it wasn't present on older platforms and it was difficult to backport it. Maybe I should take a look at it once again, but for now there's no way to get that effect below Lollipop.

**Comment by Teja-Konjeti** [comment]
sorry, I dunno how you implemented it but the library is working fine with the support recycler view but has that problem with carbon, I'll upload the sample tomorrow morning (in my time :P) do check it!

**Comment by Teja-Konjeti** [comment]
Sample - https://github.com/Sai-Teja/CarbonBug

**Comment by Teja-Konjeti** [comment]
Just change the RecyclerView in XML to Support RecyclerView and EdgeEffect Works!
Nd if you add a ItemDecoration your EdgeEffect will work.

**Comment by ZieIony** [comment]
I just run your sample and EdgeEffect is there. Emulator with API 19.

**Comment by Teja-Konjeti** [comment]
Yah! Comment out the line with decoration and you won't see EdgeEffect

**Comment by ZieIony** [comment]
The bug was connected to the fact that Android layouts don't call draw(Canvas) when there's no background set. Setting RecyclerView's background to anything turns that optimization off and EdgeEffects are drawn.

The code is fixed and pushed, so you can use it already. Checked on your app.

Thank you very much for your help.

**Comment by Teja-Konjeti** [comment]
You are welcome.. And I think you can use VelocityTracker in the android apis to implement absorption effect and I don't see why we can't back port it. It's pure math right?
I hope you will implement it atleast for lollipop, my app looks very bad without it...

**Comment by ZieIony** [comment]
There you go. It works on all platforms for all scrollable views (RecyclerView supports only vertical scrolling for now). It was pretty difficult to implement because one of needed methods (was it onAbsorb?) was private. Apparently it has changed. My absorbtion is very simple, without VelocityTracker, but should work fine.

There's an issue for absorbtion effect: #229

**Comment by Teja-Konjeti** [comment]
Thanks! :)
