### ISSUE TITLE
Can't use FAB-menu. (version 0.12.0)

### ISSUE THREAD

**Issue by Z3r0byte** [ZieIony/Carbon#228]
Hello,

After your reply on my previous issue, I updated to 0.12.0, but i still have the same problem:
`Error:(18) No resource identifier found for attribute 'carbon_menu' in package 'com.z3r0byte.magi'`
But when I compile your sample app, everything is fine. How do I fix this?

Thanks in Advance,

Z3r0byte

**Comment by ZieIony** [comment]
Oh, you're right, FloatingActionMenu wasn't ready in 0.12.0. The code is named 0.12.0, but it's because I didn't make a release since then. Sorry for the previous answer then.

As FloatingActionMenu is not released yet, you can:
- wait
- use JitPack
- clone Carbon and use it as a local module
- copy FloatingActionMenu and its resources to your code

**Comment by Z3r0byte** [comment]
OK, thank you for your answer. Ill try one of these options.
