### ISSUE TITLE
BottomBar shadow error in prellollipop

### ISSUE THREAD

**Issue by ayalma** [ZieIony/Carbon#235]
hi .
this is bottom bar output in lollipop device : 
![bottom bar in lolipop](https://cloud.githubusercontent.com/assets/15701316/14466598/bc882516-00ec-11e6-8a35-08cdbd6878c2.png)
and this is output in preLollipop device:
![bottom bar in pre lolipop](https://cloud.githubusercontent.com/assets/15701316/14466625/d6d1ab86-00ec-11e6-994e-a5c60211b403.png)
and there is no shadow in older device.

**Comment by ZieIony** [comment]
There is a shadow, but it's shifted too much to actually be seen. From time to time I'm tweaking shadows a bit to make them look like on Lollipop, but it's difficult due to differences between my implementation and the original one. Bottom bar is new and I've never tried shadows on views placed at the bottom. I'll try to make it more visible.

**Comment by ZieIony** [comment]
fixed
