### ISSUE TITLE
ViewAnimationUtils.createCircularReveal()  Compatibility!

### ISSUE THREAD

**Issue by reaper12** [ZieIony/Carbon#250]
I used ViewAnimationUtils.createCircularReveal()  in my code,but I found cornerRadius will be failure in the process of animation execution

**Comment by ZieIony** [comment]
What do you mean by 'cornerRadius will be failure'? The carbon_cornerRadius attribute on API 5.0+ uses ViewOutlineProvider to cut corners. It's a Lollipop's feature and I can't do much about it. On lower APIs ViewAnimationUtils.createCircularReveal() doesn't work at all, because Google didn't implement it for pre-Lollipop.
