### ISSUE TITLE
Add canvas fallback in ShadowGenerator

### ISSUE THREAD

**Issue by jakub-swierk** [ZieIony/Carbon#26]
There is another way for generating shadows. Using only paint shadow layer.

Check code below, and if you don't have any objections i can add pull request in next week.

TODO:
- Check performace.

Prof:

``` java
class ShadowView extends View {
    private Paint paint = new Paint();
    private RectF rect = new RectF(50, 50, 150, 150);

    private float lerp(float a, float b, float t) {
        return a * (1.f - t) + b * (t);
    }

    private ShadowView(Context context) {
        super(context);
        paint.setAntiAlias(true);
    }

    @Override
    protected void onDraw(Canvas canvas) {
        long tms = new Date().getTime();
        float t = Math.abs((tms % 8000) - 4000) / 4000.f;
        float t2 = Math.abs((tms % 2000) - 1000) / 1000.f;
        float corner = lerp(0, 100, t2);

        paint.setShadowLayer(lerp(3, 38, t), 0, lerp(1, 19, t), ((int) (lerp(0.12f, 0.30f, t) * 0xFF)) << 24);
        canvas.drawRoundRect(rect, corner, corner, paint);
        paint.setShadowLayer(lerp(2, 12, t), 0, lerp(1, 15, t), ((int) (lerp(0.24f, 0.22f, t) * 0xFF)) << 24);
        canvas.drawRoundRect(rect, corner, corner, paint);
        paint.setColor(0xFFFFFFFF);
        canvas.drawRoundRect(rect, corner, corner, paint);

        ViewCompat.postInvalidateOnAnimation(this);
    }
}
// ((FrameLayout) findViewById(R.id.container)).addView(new ShadowView(this), new ViewGroup.LayoutParams(200, 200));
```

PS. warsztatowicz.. :)

**Comment by ZieIony** [comment]
Hello mister Świrus and thank you for the suggestion! We should have a beer one day.

I was considering several shadow rendering techniques:
- gradients & 9-patches. Very fast and lightweight, but this approach doesn't support arbitrary shapes. Shadows can't be configured easily.
- setShadowLayer. Pretty fast and easy to implement. Works only with software layers. Bad blur quality.
- RenderScript. Slow, needs the RenderScript library. Works in all cases, fallbacks to software on older devices, uses Gaussian blur. 

_Paint.setShadowLayer_ works only with software layers, so this fallback would work only on devices with API <=13. More recent phones would have to turn the hardware acceleration off. This may lead to noticable performance issues. The second thing is that the shadow layer uses box blur, which is not what I would like to have.

That's why I didn't pick that technique. Is there any particular reason for the fallback? Do you have any problems with RenderScript?

**Comment by jakub-swierk** [comment]
I have only one reason: `android.support.v8.renderscript.RSRuntimeException: Error loading RS jni library: java.lang.UnsatisfiedLinkError: Couldn't load RSSupport: findLibrary returned null
`
It's ARMv6 phone where RS isn't supported.

**Comment by ZieIony** [comment]
Good point, RenderScript doesn't work on ARMv6.

If you wish, you can create a pull request with your changes. I guess you would have to test number of cases:
- shadows for arbitrary shapes,
- translucent views,
- animated views,
- clipping in layouts.

Beside the rendering code, you need a method to detect if the device can run RenderScript.

I would rather go with software blur implementation, because the current pipeline is well tested and supports all cases. The software implementation could use Gaussian blur. The only concern is the performance.

**Comment by jswirus** [comment]
Ok.
At first i must find a way to avoid crashing, native library is loaded in static initializer of RenderScript.

**Comment by ZieIony** [comment]
I just uploaded a very simple blur implementation for ARMv6. I need some time to test it, implement Gaussian blur and optimize it, but if you wish, you can check it by yourself. Seems like it's working pretty fast (for now the quality is bad though).

**Comment by jakub-swierk** [comment]
Checked and sended pull request with small fix.

**Comment by ZieIony** [comment]
I'm sorry for the delay. Your change looks good, let's try it. I'm curious if it really covers all scenarios.

**Comment by ZieIony** [comment]
I'm opening a new issue regarding quality of the fallback shadows.
