### ISSUE TITLE
Performance issue with scrollview and EdgeEffect

### ISSUE THREAD

**Issue by galibimtiaz** [ZieIony/Carbon#276]
Using scrollView make the layout very lackey, Specially when EdgeEffect shows up from top or bottom.

**Comment by ZieIony** [comment]
ScrollView doesn't do much except adding these edge effects. EdgeEffect class is taken from Android sources. That's why it shouldn't slow your application down more than regular ScrollView with animated EdgeEffect.

Maybe you could simplify your layout to gain some performance? If you don't need edge effects, you can use `android.widget.ScrollView` for the same effect.

**Comment by galibimtiaz** [comment]
I was running carbon demo in both of my devices (Sony Xperia S and Huawei p9) , in p9 things are really smooth but in Xperia S EdgeEffect is killing it, I mean when ever it poops up it gets nasty. 

But in the same device I was using usual android recyclerview with EdgeEffect but it dose not seems put any issue at all.

**Comment by ZieIony** [comment]
I was able to reproduce your issue on my Samsung. EdgeEffect is essentially a large, squashed, transparent circle. The official implementation of EdgeEffect relies on clipping and apparently it doesn't work well, at least on some devices. I don't know why Google's RecyclerView was working smoother for you though.

The fix is in the repo.
