### ISSUE TITLE
EditText setError draw icon only once.

### ISSUE THREAD

**Issue by galibimtiaz** [ZieIony/Carbon#279]
![screenshot_20170412-022303](https://cloud.githubusercontent.com/assets/7352498/24929485/e7b63f2a-1f27-11e7-8522-e0f9034831f9.png)

EditText setError works for some sec , right after it loose focus it only draw circle but not the icon.

**Comment by ZieIony** [comment]
What is the icon? I assume that it is the icon, but with tint, so it looks like a circle.

**Comment by ZieIony** [comment]
Clearing tint on EditText was causing an NPE. I just pushed an update. To clear tint just set tint to null.

**Comment by galibimtiaz** [comment]
It was just the usual error icon. Let me check the update.

**Comment by galibimtiaz** [comment]
Ok now its kinda embarrassing , how can I get the latest update of this library in my project using gradle  ?
Followed from your sample project I tried -

dependencies {
compile 'com.github.ZieIony.RandomData:person:4b76016d78'
}

but it dose not seems to work.

is there any way I can use the  latest update without downloading it as a zip file ?

**Comment by ZieIony** [comment]
RandomData is just a library used for generating random data for samples and in Samples it should work without any additional configuration. You don't need it to use Carbon. 

To use it you have to add JitPack as a source of Maven dependencies:
```
allprojects {
    repositories {
        maven { url 'https://jitpack.io' }
    }
}
```

See: https://github.com/ZieIony/RandomData

**Comment by galibimtiaz** [comment]
Thanks but I was asking how to get the latest Carbon which you update very often,
Right now I am using 
compile 'tk.zielony:carbon:0.14.0'

Its not the latest one right ? it was updated in Feb 10. 

Now to get the latest update I am downloading carbon as a zip file. So I was looking for a way to get it with gradle.

I was just testing RandomData to see if it works,

**Comment by ZieIony** [comment]
Oh. Yes, all the things I'm updating every day are available only as a source code. You have to clone the repo, build the aar and include it in your project as a library module. I know that it's not very convenient, but in that way you can get each fix as soon as possible. You can probably write a short script to make that easier:

```
git pull
./gradlew clean assembleRelease
cp carbon/build/outputs/aar/carbon-release.aar your-project-destination/carbon/carbon-release.aar
```

A while ago it was possible to use JitPack to get an aar from sources automatically. Pretty much like RandomData you mentioned. I believe it doesn't work now, because JitPack doesn't provide ConstraintLayout library (which is needed to compile Carbon).

The recent bugfixes don't seem to be critical and I'm in the middle of updating other things. That's why I don't want to release to Maven.

**Comment by galibimtiaz** [comment]
Ok , thanks, You can delete this comments about library adding since its not directly connected with the issue here.
