### ISSUE TITLE
Some question about FloatingActionButton.

### ISSUE THREAD

**Issue by galibimtiaz** [ZieIony/Carbon#286]
I have several things to ask about floating action button.

1. Why did you use raw svg when android studio already support vector drawable ?
And putting vector drawble in floating action button give an error saying "When using VectorDrawableCompat, you need to use app:srcCompat. " which is not working.

2. To change background color "android:background" seems works but in editor it shows a square box instead of a fab. And the icon also seems to be tinted by default.

3. How do I change my action menus color ?

**Comment by galibimtiaz** [comment]
I am using fab on my mapView and when action menus pops up my mapview stop listening to touch events( It stops moving ) until action menus are in hidden state again. Can I not interrupt the other touch event like map view when action menu pops up or can I make my screen background deem when action menus pops up ?

**Comment by galibimtiaz** [comment]
I was able to change fab menus color by setting up theme, it will be better if user don't have to put a theme  instead they can edit it from xml.

**Comment by ZieIony** [comment]
Ad. 1. When I started working on Carbon, VectorDrawableCompat wasn't there yet. And the reason I decided to keep SVGs is that Android's vector format doesn't support transformations, text, gradients and other things SVG does. Using SVGs is also faster as I don't have to convert files from Inkscape/Ilustrator.

Ad. 2.  This is because Carbon's FAB uses masking to get its shape, which is not supported in the editor. Carbon uses tons of things which are not supported by Android Studio. I could add an edit-mode-only background to make it round in the editor. Let me make an issue for that (#287). Tinting is intended - FAB's icon color is a part of theme, so it should change with theme change.

Ad. 3. I guess there's no way to change colors right now. Let me think about it. FloatingActionMenu is a popup, so it has all its default properties. It's possible to make it pass events through. Dimming should be done by the user.

**Comment by galibimtiaz** [comment]
Ok I have another question, How do I add onClickListener on a Floating Action Menu ,I can't find view by id,  it keep returning null.

**Comment by ZieIony** [comment]
You can't do that as the menu is shown in a popup window. There's a method to set listeners for all menu items. It works like the regular menu listener:

```
setOnMenuItemClickListener(MenuItem.OnMenuItemClickListener listener)
```

**Comment by galibimtiaz** [comment]
Thanks, that saved my life, I was getting frustrated because I could not find something that suppose to be so simple.

**Comment by ZieIony** [comment]
![image](https://cloud.githubusercontent.com/assets/10180628/25204727/2a546c2a-255f-11e7-9a7f-da3fe232164b.png)

**Comment by ZieIony** [comment]
I've added support for app:srcCompat and a method to get FloatingActionMenu from FloatingActionButton. The latter should be enough to dim background and change all properties of menu, just like you would with a simple popup.
