### ISSUE TITLE
I cant use this

### ISSUE THREAD

**Issue by mahdighaemi123** [ZieIony/Carbon#315]
Hi 
my name is mahdi I 15 years old 
sorry i not good at english
i from iran
i cant use  carbon
how i can use carbon
i import carbon error :Error:Already seen doctype.
i use carbon like Error:Failed to resolve: annotationProcessor
please send carbon as library to github like  compile 'fr.avianey.com.viewpagerindicator:library:2.4.1.1@aar'
thanks

**Comment by ZieIony** [comment]
Hello there

15 yrs old and programming? It's pretty cool. And your english is quite understandable, so don't worry.

Carbon is not available like the library you mentioned, because of some problems with Google tools. You can import the current (pretty old) version using the _compile_ clause:

`compile 'tk.zielony:carbon:0.14.0'`

or the most recent version (including colored shadows, new themes and other things) using JitPack:

top level (project's) _build.gradle_
```
allprojects {
	repositories {
		...
		maven { url 'https://jitpack.io' }
	}
}
```

_build.gradle_
```
compile 'com.github.ZieIony.Carbon:carbon:853822ce5f'
```

Please remember to setup RenderScript, enable data binding and use Carbon's theme just like it's described in the installation section: https://github.com/ZieIony/Carbon/wiki/Installation

I plan to release `0.15.0` as soon as the Google's tools become stable. That would make the whole setup process more convenient.

**Comment by mahdighaemi123** [comment]
Thanks
