### ISSUE TITLE
app:carbon_elevationShadowColor problem

### ISSUE THREAD

**Issue by reaper12** [ZieIony/Carbon#318]
app:carbon_elevationShadowColor and app:carbon_cornerRadius together there will be a problem:The rounded no shadow.

**Comment by ZieIony** [comment]
What is your issue exactly? There's no shadow, when the widget has rounded corners? Or the corners are not rounded when shadow color is set?

Please make sure that
- a widget's parent is a Carbon layout
- elevation of the widget is set to a non-zero value
- the shadow's color is set to a value you can actually see

You can also play with the sample code. There are at least two samples (widgets/buttons and features/shadows) where you can see the colored shadow feature in action.

If nothing helps, please post some code or a tiny application showing your issue.

**Comment by reaper12** [comment]
look feature/ShadowActivity.
<img width="373" alt="wx20170904-204148 2x" src="https://user-images.githubusercontent.com/13657190/30026933-8003123e-91b1-11e7-8dae-0d30aef7d690.png">

**Comment by reaper12** [comment]
Four corners no shadow

**Comment by ZieIony** [comment]
It's a limitation of the current implementation. I'll be working on it, but for now there's nothing you can do. Rectangular and circular shapes should look better than rounded rectangles

**Comment by ghost** [comment]
I have copy-pasted your sample code from activity_shadow.xml
In your demo app shadows look fine, but I have the same issue as reaper12 had.
More than that, when I set app:carbon_elevationShadowColor to red color, color seems to be mixed with grey. I want the shadow to be just red

my app:
![_my](https://user-images.githubusercontent.com/16720215/50955679-d4f0a200-14ca-11e9-8ec7-ecfb2304930e.png)

your app:
![_sample](https://user-images.githubusercontent.com/16720215/50955695-dcb04680-14ca-11e9-8dd4-f9ee66f93e6f.png)

**Comment by ZieIony** [comment]
This issue is a bit outdated since I rewrote the shadows recently ([Nov 21](https://github.com/ZieIony/Carbon/commit/a56b1ceeb4ab2e201d5b261c250ab66e80cb423a)) to support cut corners and other fun shapes. It's not really tested yet and the release is yet to happen. Maybe this weekend?

The gray color can be the result of the fact that since Android 9 there are two colors used to color spot and ambient shadow independently. I wouldn't care about it too much - Carbon 0.16.0's shadows won't have that due to specifics of the implementation I'm moving to.

**Comment by ghost** [comment]
Grey color appears for my app on both API 23 and API 28. 
I've changed all buttons' shadow color to pure red and I get this

API 23 my app
![red](https://user-images.githubusercontent.com/16720215/50959831-e63eac00-14d4-11e9-868f-9bc07ceaf69f.png)

API 23 your app
![red3](https://user-images.githubusercontent.com/16720215/50960850-6239f380-14d7-11e9-8261-722b94f2a2c6.png)

API 28 my app
![red2](https://user-images.githubusercontent.com/16720215/50959835-eb036000-14d4-11e9-83b2-87bba3e98cb3.png)

API 28 your app
![screenshot_1547114402](https://user-images.githubusercontent.com/16720215/50961039-d5dc0080-14d7-11e9-8d38-1950cea0d61e.png)

**Comment by ghost** [comment]
also I don't understand why shadows in my test app are so different from your sample app (I run both apps on the same device)

**Comment by ZieIony** [comment]
There's a couple of options:

 - I suppose that you're using Carbon 0.15.3 and you're building the sample app from the sources. The sources contain different implementation of shadows than 0.15.3. I guess that's the reason for different look between you app and the sample app.
 - API 28 has native implementation of colored shadows, which works only with the most recent Carbon (0.15.3 doesn't have that yet).
 - There are two implementations of shadows in 0.15.3 - software and RenderScript based. Both give slightly different results. Maybe RenderScript in your app fails to init because of whatever reasons?

As I wrote earlier, the implementation has changed and will be released as 0.16.0. It will make the shadows look more consistent, get rid of RenderScript and fix the issue raised by reaper12.

**Comment by ZieIony** [comment]
My most recent idea was to use MaterialShapeDrawable from material-components 1.1.0 to draw colored shadows. Well, it's been a month and I still can't make it work. The list of issues is quite long:

 - The shadow is too dark and too thick. It looks a lot different than the Lollipop's one.
 - It doesn't draw corners when corner radius is 0dp. It draws strange artifacts on Android 4.x (as you can see on the screenshot).
 - It draws another strange artifacts on Android 5+, when corner radius is in range (0,1].
 - It allocates a new software bitmap for each draw call, so its performance is bad.
 - It uses clipPath(), which is not hardware accelerated on API 14 - 17, so I cannot get rid of that software bitmap.
 - It adds insets for a stroke, if set, so it's not possible to align widgets content correctly and use stroke at the same time.
 - Vertical shadow offset breaks things if it's drawn manually. It can be fixed by using drawShape() with shadow's color, but then xferemode's clear clears wrong part of the drawable, so I have to clear manually.
 - If I copy MaterialShapeDrawable to Carbon, I can't use material-component's Treatment classes, because there are package-private things I need to access. I need to copy in order to fix its drawing issues.

![image](https://user-images.githubusercontent.com/10180628/52166799-53c7ac00-2712-11e9-8489-2a7174022e32.png)

**Comment by ZieIony** [comment]
Another update. I was able to get rid of grey rendering artifacts, get rid of clipPath() and get rid of bitmap allocations. Performance is ok, but there still are small drawing issues where shadow parts connect. I need to test it on a couple of devices and maybe fix these drawing issues.

![image](https://user-images.githubusercontent.com/10180628/52377869-67eb1080-2a66-11e9-8832-694c1884aea3.png)

**Comment by ZieIony** [comment]
I just uploaded Carbon 0.16.0 using MaterialShapeDrawable for shadows. It still has minor issues, but androidx and other updates can't wait forever.

As this issue seems to be addressed, I'm closing it. Please open another one if neccessary.
