### ISSUE TITLE
RenderScript Duplicate zip entry 

### ISSUE THREAD

**Issue by BraunreutherA** [ZieIony/Carbon#319]
Hi, 

thanks for this awesome library! 
Sadly I'm getting this error on Android 4.x devices: 

Error:Execution failed for task ':app:transformClassesWithMultidexlistForDevDebug'.
> java.io.IOException: Can't write [/Users/Alex/Desktop/development/pyck/app.android/app/build/intermediates/multi-dex/dev/debug/componentClasses.jar] (Can't read [/Users/Alex/Desktop/development/pyck/app.android/app/build/intermediates/transforms/desugar/dev/debug/4.jar] (Duplicate zip entry [4.jar:android/support/v8/renderscript/ScriptIntrinsicBLAS$Uplo.class]))

```
    compile('tk.zielony:carbon:0.15.0.1') {
        exclude group: 'com.android.support.v8', module: 'renderscript'
    }
```

Already tried excluding renderscript but it doesn't help here. Do you have some recommendations on fixing this? 

Thanks and best
Alex

**Comment by ZieIony** [comment]
Hello there.

I'm aware of this issue. The deal is that the most recent Gradle adds RenderScript for each declaration in *.gradle files without checking for duplicates. If possible, please remove additional RenderScript declarations.

I won't be able to provide any further help until Monday, because I don't have access to my laptop. Please be patient  :)

**Comment by BraunreutherA** [comment]
Hi, 

thanks for the advice! I only had to remove renderscript from my app.gradle file - I think you could make this more clear in the docs, I thought I have to add it so that carbon works.

**Comment by ZieIony** [comment]
Cool.

I suppose I could do that. RenderScript declaration was needed for about two years. Now it's not and I've removed that from the installation guide. I thought that it would be enough.
