### ISSUE TITLE
Cant install Carbon

### ISSUE THREAD

**Issue by Nastromo** [ZieIony/Carbon#320]
Tried to install Carbon and got this

![bitmap](https://user-images.githubusercontent.com/29987943/30651796-66c1d6fe-9e2f-11e7-923f-38efe55f47ae.png)

Absolutely new application without any activity yet.

My steps:
1. File => Project structure => myapp => dependencies => add from maven => find this "tk.zielony:carbon:0.15.0" ADD

2. Then manually add this into build.gradle (module app).:
dataBinding {
        enabled = true
    }

After these steps I have had the errors on the screen upper.
What have I done wrong?

Tried to do the same in Android Studio 3.0 but also have problems with manifest file.

Please help. Really need those colored shadows :) and thanks in advance!

**Comment by ZieIony** [comment]
You need Android Studio 3.0 and Google repositories to work with Carbon. To install Google repositories make sure that you have such section in your main `build.gradle`:

```
allprojects {
    repositories {
        jcenter()
        maven { url 'https://jitpack.io' }
        google()             // google repositories
    }
}
```

Use `0.15.0.1` instead of `0.15.0` - it contains an important bugfix.

What are these issues in the manifest you mentioned?

**Comment by Nastromo** [comment]
In Android Studio 3.0 have this error:

![bitmap1](https://user-images.githubusercontent.com/29987943/30656321-64cd215c-9e3c-11e7-8cd8-dd5413738c75.png)

My steps:
1. Instal Android Studio
2. Create absolutely new Project.
3. Create Empty Activity.
4. Install Carbon new Version File => Project structure => myapp => dependencies => add from maven => find this "tk.zielony:carbon:0.15.0.1" ADD
5. After this, Gradle try to build and then this error with manifest (on screen).

I didn't do anything in code or any xml file. What can it be?

**Comment by ZieIony** [comment]
Until the most recent release Gradle was using the most recent specified dependency version. Now it aborts compilation and throws this error. You're getting it, because there are two different versions of one library in the project. This issue was already reported to Google. See: https://issuetracker.google.com/issues?q=attribute%20meta-data%20version%20is%20also%20present

I suppose you can fix this by manually excluding subdependencies. Keywords for googling: https://www.google.pl/search?q=gradle+exclude+transitive+dependency

**Comment by Nastromo** [comment]
I just have started learn Android. I fill difficult to manage this issue by myself. If you could provide some instruction to solve this issue many will be thankful to you, I think.

**Comment by ZieIony** [comment]
Could you please share your simple app with that issue with me?

**Comment by Nastromo** [comment]
Here is a git repo with simple app that had an error occurred:
https://github.com/Nastromo/FaceLoca

Nothing special, just a new app with no any line of new code.
This app give me an error on the screen below:
![bitmap2](https://user-images.githubusercontent.com/29987943/30689866-01442da8-9ecb-11e7-8f5f-78785b6d4e12.png)

**Comment by ZieIony** [comment]
So, the issue is that Google libraries declare its versions in manifests. When there are two different versions, manifest merger fails. To make it work, all dependencies have to be in the same version.

First, check the dependency tree to see what's wrong:

```
./gradlew app:dependencies
```

This command should print a dependency tree. What you can see is that Carbon uses different dependencies than you (26.0.1 vs 26.1.0). There's a couple of dependencies which are present only in Carbon (design and gridlayout).

Then either: 

A. Declare the missing dependencies in your version. Gradle will discard outdated dependencies used by Carbon.

```
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support:design:26.1.0'
    implementation 'com.android.support:gridlayout-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation('com.android.support.test.espresso:espresso-core:3.0.1', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation 'tk.zielony:carbon:0.15.0.1'
}
```

B. Remove your Google dependencies. Gradle will use these declared by Carbon.

```
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    testImplementation 'junit:junit:4.12'
    androidTestImplementation('com.android.support.test.espresso:espresso-core:3.0.1', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation 'tk.zielony:carbon:0.15.0.1'
}
```

Remember to specify source comatibility. Carbon uses Java 1.8.

```
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```

**Comment by Nastromo** [comment]
Looks like it works. Done!
Thank you very much. So now I will try to add some color shadow to my shapes.
