### ISSUE TITLE
AS3.1.2   i can't use this

### ISSUE THREAD

**Issue by EastUp** [ZieIony/Carbon#343]
![issue](https://user-images.githubusercontent.com/17868269/40043693-df0b486a-5857-11e8-862a-86613b5c5548.jpg)
This is my gralde problem. Please help to check it.

**Comment by ZieIony** [comment]
Do you have Java 1.8 compatibility settings enabled? Like this:

```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
```

**Comment by EastUp** [comment]
yes,i put this in android{

}

**Comment by ZieIony** [comment]
Could you please post your `build.gradle` file? Or prepare a minimal working example of your issue and post a github link? Your issue seems to be related to language version used by your program. See: https://stackoverflow.com/questions/49512629/android-studio-error-default-interface-methods-are-only-supported-starting-with

**Comment by EastUp** [comment]
```
apply plugin: 'com.android.library'

android {
    compileSdkVersion 27



    defaultConfig {
        minSdkVersion 17
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    dataBinding {
        enabled = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
   }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:25.3.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation('com.android.support.test.espresso:espresso-core:3.0.1', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    api('tk.zielony:carbon:0.15.0.1') {
        exclude group: 'com.android.support', module: 'support-v4'
        exclude group: 'com.android.support', module: 'appcompat-v7'
        exclude group: 'com.android.support', module: 'gridlayout-v7'
        exclude group: 'com.android.support', module: 'design'
    }
    api 'com.github.bumptech.glide:glide:3.7.0'
    api 'com.android.support:recyclerview-v7:25.3.1'
    api 'com.lzy.net:okgo:3.0.4'
    api 'com.orhanobut:logger:2.1.1'
    api 'pub.devrel:easypermissions:1.2.0'
    api 'org.greenrobot:eventbus:3.0.0'
    api 'com.alibaba:fastjson:1.2.44'
    api 'com.google.code.gson:gson:2.8.2'
    api 'com.github.dmytrodanylyk.shadow-layout:library:1.0.3'
}
```

above is my build.gradle

**Comment by ZieIony** [comment]
I tried to reproduce your issue, but without success. I noticed that you're using really old versions of support libraries. I would suggest updating gradle plugin, sdk tools and support libraries to the most recent versions. Default interface methods and other things from the error message are supported via desugaring since Android Studio 3.0 (and the corresponding toolchain).

**Comment by EastUp** [comment]
gradle is okay, but I'm running the error on my phone.

**Comment by EastUp** [comment]
gradle is okay, but I'm running the error on my phone.

**Comment by EastUp** [comment]
gradle is okay, but I'm running the error on my phone.
my gradle tools is   classpath 'com.android.tools.build:gradle:3.1.2' and support libraries update to version 27.1.1

**Comment by EastUp** [comment]
when i back to use 'tk.zielony:carbon:0.14.0,' it's ok, but carbon_cornerRadius is useless, i don't know why

**Comment by ZieIony** [comment]
What do you mean by "gradle is okay, but I'm running the error on my phone"? You're clearly getting a compilation error. Does it work on other phones or an emulator?

0.14.0 wasn't using Java 8 features - that's why you're not getting these errors on previous version.

What do you mean by "carbon_cornerRadius is useless"? I don't really remember all changes introduced in 0.15.0, but I guess that corner radius was working earlier.

**Comment by EastUp** [comment]
i konw why,but there has still have one question
 carbon_cornerRadius for carbon.widget.RelativeLayout is useless but it  work for carbon.widget.Button

**Comment by EastUp** [comment]
i konw why carbon_cornerRadius is useless,because my activity  use  android:hardwareAccelerated="false"
thank you
