### ISSUE TITLE
It's not new on maven

### ISSUE THREAD

**Issue by EastUp** [ZieIony/Carbon#347]
![585d2772-c1dd-468c-b13a-d3117b7bc9a7](https://user-images.githubusercontent.com/17868269/40894579-447c3daa-67dd-11e8-9fa7-f4c9ce42bc32.png)
TextView still not implement StrokeView
Editext still not implement RoundedCornersView

**Comment by ZieIony** [comment]
The screenshot suggests that you're looking at the previous version. The feature you're looking for is present since release 0.15.1 or commit 2c22fa7967. Please update and check again. If that's more convenient you can use JitPack or compile the library manually.

https://search.maven.org/#artifactdetails%7Ctk.zielony%7Ccarbon%7C0.15.1%7Caar

**Comment by EastUp** [comment]
The version 0.15.1 is correct,  Your document should also be updated, thank you
