### ISSUE TITLE
Pixelated corners on carbon.widget.FrameLayout

### ISSUE THREAD

**Issue by ildar2** [ZieIony/Carbon#351]
When I try to apply round corners on FrameLayout, they get edgy and pixelated. How to make them smooth?
<img width="326" alt="pixelated corners" src="https://user-images.githubusercontent.com/13849510/41956609-09dbf25e-7a06-11e8-8230-a2a1cd4bcc35.png">

               <carbon.widget.FrameLayout
                                android:layout_width="match_parent"
                                android:layout_height="wrap_content"
                                android:layout_marginBottom="24dp"
                                android:layout_marginLeft="16dp"
                                android:layout_marginRight="16dp"
                                android:layout_marginTop="28dp"
                                app:carbon_cornerRadius="5dp"
                                app:carbon_elevation="2dp">

**Comment by ZieIony** [comment]
That's interesting. What kind of device is this?

**Comment by ildar2** [comment]
Device is Xiaomi 5A

Problem solved by adding 
                                    `app:carbon_elevationShadowColor="@color/black"`
and 
                                    `android:background="@color/white"`
<img width="323" alt="normal" src="https://user-images.githubusercontent.com/13849510/41960621-0deb86fa-7a12-11e8-9f33-1288b3c5b934.png">

Although if you add `app:carbon_elevationShadowColor` only, you'll get weird result:
<img width="325" alt="wierd shadow" src="https://user-images.githubusercontent.com/13849510/41960634-1704245e-7a12-11e8-8e3c-d9f00af1e9b5.png">

**Comment by ZieIony** [comment]
I didn't notice that you don't have any background set. All the results you're getting are not bugs. The correct solution is to set background to any nontransparent color, because if the widget is transparent, the shadow can be seen through it. Changing shadow color will cause the widget to use alternate, software method of rendering shadows on Android 5.0+, so it's not recommended unless you really need colored shadows.
