### ISSUE TITLE
[SUGGESTION] Could use with splitting each component into its library

### ISSUE THREAD

**Issue by Akshshr** [ZieIony/Carbon#353]
Hey there, 

A kind suggestion, would be really helpful to split each component into its library so one can easy pick out the view as per their need. 

Would make it much simpler :) 👍

**Comment by ZieIony** [comment]
Hello,

Widgets are connected together and use common code, styles and other resources. I don't think that it would be possible to extract anything without rewriting the library and breaking backwards compatibility.

It doesn't really make sense to provide widgets without layouts, because layouts draw shadows for widgets. Same goes for RippleDrawable, base view classes, rounded corners, SVG support and font support - these are used by most of the widgets. Extracting these features is not possible.

Extracting widgets while keeping all features present wouldn't really make the out libraries smaller. In fact, using two or three widgets would mean including a lot of duplicated code.

If you're thinking about reducing the size of apps using Carbon, I guess the best bet is to use ProGuard.
