### ISSUE TITLE
Need feature of RenderingMode

### ISSUE THREAD

**Issue by ghost** [ZieIony/Carbon#396]
Hello, Zielony. I find that RenderingMode feature is removed in version 16.0.1. This days I faced some problem when I use elevation shadow above android 5.0. As I see, system elevation will make some animation when scroll the shadow view child in RecyclerView or ViewPager. It seems very strange and the shadow will be first be cropped and regular later. When I change to software RenderingMode in version 15.0.3, the shadows keep regular. So I wish you to add this feature again and attach it a xml attribute. 

screenshot:
![Screenshot_1573700341](https://user-images.githubusercontent.com/53754839/68823423-6e867280-06df-11ea-828f-9c9836f301ba.png)

**Comment by ZieIony** [comment]
RenderingMode was introduced to fix problems with RenderScript rendering. It's not present since 0.16.0, because Carbon doesn't use RenderScript anymore.

Your issue seems to be caused by the layout of the item. It's a very popular struggle and it's not related to Carbon as on Lollipop Carbon uses native shadows. Your cards are contained in an another layout, which clips card's shadow and produces the effect you're observing. Try removing the parent layout to position cards directly in the ViewPager/RecyclerView.

See: https://stackoverflow.com/questions/34518426/elevation-shadow-is-clipped
