### ISSUE TITLE
carbon.widget.InputLayout cannot be cast to com.google.android.material.textfield.TextInputLayout

### ISSUE THREAD

**Issue by kangkosw** [ZieIony/Carbon#414]
carbon.widget.InputLayout cannot be cast to com.google.android.material.textfield.TextInputLayout

can not use carbon.widget.InputLayout with https://github.com/afollestad/vvalidator#validation-results

**Comment by ZieIony** [comment]
Well, carbon.widget.InputLayout doesn't extend com.google.android.material.textfield.TextInputLayout, so this is correct. InputLayout by design just provides additional buttons and labels to other views, so I think that the inner view is what should be validated.

I don't know the library you linked, so it's hard for me to tell anything more. If that library is easy to extend, maybe you could add your own validator to support widgets that are not supported by default.
