### ISSUE TITLE
how can i change shadow direction? is Any way to do that?

### ISSUE THREAD

**Issue by milinocean** [ZieIony/Carbon#418]

**Comment by ZieIony** [comment]
Not really. Shadows in all three - Android, androidx and Carbon - are fixed to be cast from a light source hanging above the screen. Using Android you can override system constants, but that's a bit hacky and will affect all views in your app (I think). Also native shadows take horizontal position of the light into account. Using both androidx and Carbon you can offset shadows as you wish, but there's no interface provided by views for that. The best option you have is to take the code Carbon uses to draw shadows ([like this](https://github.com/ZieIony/Carbon/blob/master/carbon/src/main/java/carbon/widget/Button.java#L701)) and use it to draw your own shadows. I think I could also add a parameter for that, but it may take a while since I'm currently spending most of my time on another project.

**Comment by W-quan** [comment]
I want the light source in center of view.  When the evevation is 1dp, the top of view doesn't have shadow but the bottom has too much. I want same shadow in each side.

**Comment by ZieIony** [comment]
Please don't add questions or requests as comments to older, closed issues as they may get lost. Post a new issue instead. Note that this quesion has already been answered and the situation didn't change since then. The light source is positioned above the screen and produces shadows you're observing by design and there's no easy way of changing that.
