### ISSUE TITLE
Seekbar ripple not working in AppCompat theme

### ISSUE THREAD

**Issue by ghost** [ZieIony/Carbon#420]
I find it should force to use carbon_Theme theme for Activitys to make Seekbar pressing ripple effect working. I don't know why and if there is any suggestion to solve this problem? I use AppCompat theme in my project.

**Comment by ZieIony** [comment]
`carbon_Theme` adds attributes required for Carbon widgets to work, just like AppCompat theme adds attributes needed by AppCompat widgets. Using other themes will cause certain things to not work because of missing attributes. If you can't change the theme for your activities, you can override it per widget using 'theme' attribute, just like in this example: https://github.com/ZieIony/Carbon/blob/master/samples/src/main/res/layout/activity_theme.xml. `carbon_Theme`s use `Theme.MaterialComponents`s as their bases, so if you used MaterialComponents themes, the transition would be really easy.

**Comment by ghost** [comment]
Thanks for you suggestion, I have fixed it.
