### ISSUE TITLE
Preview in Android Studio

### ISSUE THREAD

**Issue by tronghieubk** [ZieIony/Carbon#50]
I have problem previewing CheckBox and CardView in Android Studio, it shows NullPointerExeption.

Exception Details java.lang.NullPointerException   
at carbon.widget.CheckBox.init(CheckBox.java:79)   
at carbon.widget.CheckBox.<init>(CheckBox.java:42)   
at carbon.widget.CheckBox.<init>(CheckBox.java:37)

Also, textStyle="bold" doesn't work on carbon.widget.TextView too.

**Comment by ZieIony** [comment]
textStyle="bold" doesn't work, because Carbon overrides these simple styles with Roboto font. To get a bold typeface, you have to use:

```
gt:carbon_textStyle="bold"
```

The NPE you're getting is a bug. In preview the check drawable is not created due to lack of SVG support. I'm marking this issue as a bug. For now there's no workaround.

**Comment by ZieIony** [comment]
fixed in 0.6.7.2
