### ISSUE TITLE
PagerTabStrip text color

### ISSUE THREAD

**Issue by wrozwad** [ZieIony/Carbon#57]
They're any possibility to change text color of PagerTabStrip? I try everything and I still have black text on dark background...

**Comment by ZieIony** [comment]
PagerTabStrip uses a builder to create items. You can use any layout as a tab. To use it specify your own TabBuilder:

```
pagerTabStrip.setTabBuilder(new TabBuilder() {
        @Override
        public View getView(int i) {
            View view = View.inflate(getActivity(), R.layout.tab, null);
            TextView text = (TextView) view.findViewById(R.id.id_tab_text);
            text.setText(viewPager.getAdapter().getPageTitle(i));
            return view;
        }
    });
```

**Comment by wrozwad** [comment]
It works, thanks. But can you move tab color declaration to attribute, eg. `carbon_tabTextColor`? Or by `setTabColor()` function?

`<PL>`
Btw - wygląda na to, że pewnie nie raz skorzystam z Twojej biblioteki (albo nawet zrobię port dla andka >= 4). Przydałby się więc jakiś kontakt do Ciebie ;)
`</PL>`

**Comment by ZieIony** [comment]
I don't want to add such attribute, because there's a lot of things one could possibly tweak including text size, ripple color, tab icon, etc. Adding them one by one misses the point, so there's the Adapter approach.

Jeśli chodzi o kontakt, to można mnie znaleźć na kilka sposobów:
greenguymakesapps@gmail.com
https://plus.google.com/u/0/109054799904873578131
https://androidreclib.wordpress.com/
