### ISSUE TITLE
RecyclerView onClickListener

### ISSUE THREAD

**Issue by siavashkavousi** [ZieIony/Carbon#67]
I add these lines to my code, and just after I click on one of the items of the recyclerView it simultaneously processes on click method and and it won't wait for the item's ripple to complete
(Note: I also set setFocusable and setFocusableInTouch true but another problem arise with them which is I should click twice, first time ripple is working correctly but no call to onclick method then another click ripple isn't working correctly and onClick method works)

(Note: content is the itemView in viewHolder the same as your code, I just add click listener method to do some stuff!)

LinearLayout content = mCardView.getContent();
            RippleDrawable rippleDrawable = new RippleDrawable(R.color.carbon_ripple_dark, itemView.getContext());
            rippleDrawable.setStyle(RippleDrawable.Style.Over);
            rippleDrawable.setCallback(content);
            rippleDrawable.setHotspotEnabled(true);
            content.setRippleDrawable(rippleDrawable);
            content.addStateAnimator(new RippleStateAnimator(content));
            content.setOnClickListener(this);

**Comment by ZieIony** [comment]
The original RippleDrawable, found in Lollipop uses hardware pipeline and the new rendering thread to play all animations smoothly, even if there's any heavy computation running. Older versions of Android doesn't have that thread and that's why it's impossible to achieve Lollipop's level of smoothness. None of the backport libraries offer that.

Starting from 0.7.3, Carbon will use the original implementation, when running on Lollipop. Most of the code is already online, so you can check it if you wish.

If you'd like to get smooth, uninterrupted ripple animations, you have to delay your onClick calls by 200ms or so. Some of the other libraries offer built-in delaying, so the ripples can complete. Just keep in mind that prolonging animations can be irritating, so you have to pick as small delay as possible.

Besides that, RippleDrawable in 0.7.3 will react to state changes, so RippleStateAnimator will no longer be neccessary and the code won't be affected by any touch events.
